// <auto-generated />
using System;
using EfficientDesigner_Service.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EfficientDesigner_Service.Migrations
{
    [DbContext(typeof(LayoutContext))]
    [Migration("20201028074727_添加PropertyBinding和将Id列和时间列改为自动生成。")]
    partial class 添加PropertyBinding和将Id列和时间列改为自动生成
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("EfficientDesigner_Service.Models.Layout", b =>
                {
                    b.Property<Guid>("LayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("File")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.HasKey("LayoutId");

                    b.ToTable("Layouts");
                });

            modelBuilder.Entity("EfficientDesigner_Service.Models.PropertyBinding", b =>
                {
                    b.Property<Guid>("PropertyBindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertyName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateTime")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("PropertyBindingId");

                    b.HasIndex("LayoutId");

                    b.ToTable("PropertyBinding");
                });

            modelBuilder.Entity("EfficientDesigner_Service.Models.PropertyBinding", b =>
                {
                    b.HasOne("EfficientDesigner_Service.Models.Layout", "Layout")
                        .WithMany("PropertyBindings")
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
